### ISSUE TITLE
API: Add PC/SC support

### ISSUE THREAD

**Issue by martinpaljak** [web-eid/web-eid#16]
Described in wiki: https://github.com/hwcrypto/hwcrypto-native/wiki/PCSC-passthrough

**Comment by grakic** [comment]
If I understand this right, this future API would be implemented in hwcrypto-native and exposed by hwcrypto-extension, so one would just have to fork hwcrypto.js for custom PCSC applications like eID readers, e-wallets and such?

If it is not exposed by hwcrypto-extension then one would have to fork both the extension to expose the API and the native component (to include new extension in the allowed_extensions list of the manifest file). The code can be reused but that would probably defunct https://github.com/hwcrypto/hwcrypto-extension/issues/2

**Comment by martinpaljak** [comment]
It will be exposed via hwcrypto-extension via a messaging interface not unlike https://github.com/martinpaljak/apdu4j/wiki/JSON-Remote-EMV-Terminal (but will get some adjustments probably, based on the current state of similar interface specification efforts)

The focus of hwcrypto.js shall be in the foreseeable future on the "key/certificate level" abstraction and expose implementations that work on this level. 

A separate "hwcrypto-pcsc.js" kind of library will probably surface, that wraps the messaging interface with promises and nothing forbids from making hwcrypto.js lookalike interfaces on top of apdu chats. But that is definitely not going to be mainstream.

Bear in mind that the intended UX will be something like this:

- click some action button on a page
- get a popup "origin XX would like to get access to your smart card reader, please select a reader from the list below to continue"
- connection to the reader is opened (possibly in exclusive mode, TBS)
- a topmost UI window "origin XXX is connected to reader ZZZ, click cancel to terminate" will be present for as long as the site has the connection to the reader open

**Comment by martinpaljak** [comment]
To say it in different wording: authentication and signing interfaces are supposed to be used daily while the PC/SC passthrough is supposed to be used, but not as often as "click here to login". The idea is to enable card management operations via the browser, that divert from simple crypto operations. I see the benefit of having "plain old apdu" interface available in the browser, but I agree with the opposing camp, that it should not be an interface promoted as "this is cool, lets do all things like this". PC/SC APDU interface is an archaic error-prone relict, which is needed in real life in near future, but hopefully will not live a long life on its own. Especially in the web context, as a first class citizen.

**Comment by martinpaljak** [comment]
#47 is a separate ongoing activity, latest published beta has an otherwise finalized PC/SC interface
