### ISSUE TITLE
PKCS#7 Detached Signature

### ISSUE THREAD

**Issue by pareshchouhan** [web-eid/web-eid#49]
I am working on PDF signing using PKCS#7 Detached signatures.  
PKCS#7 requires signed DigestInfo[[1]] .  
```
DigestInfo ::= SEQUENCE {
     digestAlgorithm DigestAlgorithmIdentifier,
     digest Digest 
}
```
DigestInfo requires ```digest algorithm identifier``` to be appended with ```Message Digest```, though the hwcrypto (now web-eid.js?) only takes in message digest for signing.  

My question is  
a) Does web-eid append the digest algorithm identifier before signing the hash?  
b) If it doesn't, could you explain [pkcss11module#L306](https://github.com/web-eid/web-eid/blob/master/src/pkcs11module.cpp#L306) what the hash padding is?  

Sorry if it sounded naive, I don't have enough experience with C and Hashing to fully understand the code.

[1]: https://tools.ietf.org/html/rfc2315#section-9.4

**Comment by pareshchouhan** [comment]
I see, this does define what needs to be added https://www.ietf.org/rfc/rfc5754.txt , what about   
```
0x30, 0x31 at the starting and 
0x04, 0x20 at the ending
```

**Comment by martinpaljak** [comment]
The returned signature is shaXXXWithRsaEncryption, which includes the hash algorithm identifier. Input to  web-eid.js sign() method is the plain hash.

**Comment by pareshchouhan** [comment]
hello martin, sorry for bumping this thread, could you look into this https://stackoverflow.com/questions/44196316/pdf-signing-generated-pdf-document-certification-is-invalid-using-external-si 
please
Regards

**Comment by pareshchouhan** [comment]
@martinpaljak It was because of chrome-token-signing and web-eid outputting different results 
(my code works with chrome-token-signing and hwcrypto.js), whereas it doesn't work with (hwcrypto.js and web-eid-extension), I have no clue why
 I will uninstall everything and test it out again.

**Comment by pareshchouhan** [comment]
For same hash.
WEB-EID.js
```
988FA7D52AA80DFFE61174259AF7233E48A3678A25BB7E56358FA2DA7EF1AAFAD8F57FF66378209ED6EC51289738FB0B33036D7EF9742F8B8EFD25FBFF45794235E379519C137A6C4B8F9F191B0754FF3A80A496AF6ED0F3EE8D60E75F746E6F33F66E57455915217E3BA4E7DF3ACC893CE147C84C9B3B4B34C6FDB44A50747434241F54E378D5CF82814A2C65D48E4200E0ADF18449262D90ACEB457EA6407DB2FEF174442F110A4AB6887EE99170D21128C049801E326767EE6EA087A8A19808A4EC65F04C7A8FDC0EAB9D173B0163494F5625C7E4C75C294D5BACE9FFEE0F1F659E89811FF667E2CC70F06A01D9BAE38188588870B0A99AE2771F40FEBAA5
```
hwcrypto.js
chrome-token-signing
```
48C868C46F66C87BF0184A7572F16805E42619B6C93493E14686601FBAF224F8F61AB948FA75DBA573641ADD760078764F83F334893AF52F83405E17955099A31D69B8F1D7337398B1838FB290842F5364505843F4BC0CCA4F3A186FC2293081ACD9B98BBC973D7C6A5C85B14BF2724DCDAB51E7D62B698C08BDEDD7BB80913C75A782408298063AAECA6C6F462C166B430C6E4C3A631D7601FA22B38AA62499FB131E0743CF0C91D9BA45ABA72E2A920D5A693833ED16231C656E375CF72F0CE9F4A022E2CB516ECA000F415FF481F10F239A56379ACC212AD31036FCAC179CD8E040452D168B889D1A449E1ECCC88FC23DF735C1251DA662DF980D3EE8023D
```

**Comment by martinpaljak** [comment]
First, the two components are not supposed to be interchangeable. JS interfaces are a bit similar, but that's it.

Second, if you have issues with actual operations, do include 1) input parameters 2) certificate 3) result

**Comment by pareshchouhan** [comment]
>First, the two components are not supposed to be interchangeable. JS interfaces are a bit similar, but that's it.
I figured...
Works perfectly fine with hwcrypto.js and chrome-token-signing. 
Thanks 
Regards
